name: bottom_navigation_view
description: A set of widgets that helps you to implement bottom navigation.
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
 